name: Create Kodi Addon Release

on:
  push:
    branches:
      - main

# Add permissions needed for creating releases
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get addon info
      id: addon_info
      shell: bash
      run: |
        # Extract addon id from first line with id attribute (should be the addon tag)
        ADDON_ID=$(grep -o '<addon id="[^"]*"' addon.xml | head -n 1 | cut -d'"' -f2)
        echo "Found ADDON_ID: $ADDON_ID"
        
        # Extract addon version from first line with version attribute (should be the addon tag)
        ADDON_VERSION=$(grep -o '<addon.*version="[^"]*"' addon.xml | head -n 1 | grep -o 'version="[^"]*"' | cut -d'"' -f2)
        echo "Found ADDON_VERSION: $ADDON_VERSION"
        
        # Export as environment variables without using GITHUB_ENV
        export ADDON_ID="$ADDON_ID" 
        export ADDON_VERSION="$ADDON_VERSION"
        
        # Create a properties file and read it in the next steps
        echo "ADDON_ID=$ADDON_ID" > addon_info.properties
        echo "ADDON_VERSION=$ADDON_VERSION" >> addon_info.properties
      
    - name: Load addon info
      run: |
        source addon_info.properties
        echo "Using ADDON_ID=$ADDON_ID"
        echo "Using ADDON_VERSION=$ADDON_VERSION"
    
    - name: Create release zip
      run: |
        source addon_info.properties
        echo "Creating zip for addon $ADDON_ID version $ADDON_VERSION"
        
        # Create a clean directory for the addon
        mkdir -p "zip_release/$ADDON_ID"
        
        # Copy all files (excluding git and temp files)
        cp -r addon.xml main.py README.md changelog.txt bump_version.py resources "zip_release/$ADDON_ID"
        
        # Show what we're about to zip
        ls -la "zip_release/$ADDON_ID"
        
        # Create the zip file
        cd zip_release
        zip -r "../$ADDON_ID-$ADDON_VERSION.zip" "$ADDON_ID"
        cd ..
        
        # Verify the zip was created
        ls -la "$ADDON_ID-$ADDON_VERSION.zip" || echo "*** ZIP FILE NOT CREATED ***"
        
    - name: Create GitHub Release
      id: create_release
      run: |
        source addon_info.properties
        echo "Creating release for version $ADDON_VERSION"
        
        # Print info about what we're doing
        echo "Creating release v$ADDON_VERSION for addon $ADDON_ID"
        
        # Check for zip file
        ZIP_FILE="$ADDON_ID-$ADDON_VERSION.zip"
        if [ ! -f "$ZIP_FILE" ]; then
          echo "ERROR: Could not find zip file: $ZIP_FILE"
          pwd
          ls -la
          exit 1
        fi
        
        # Create release notes file
        echo "Kodi Addon Release v$ADDON_VERSION" > release_notes.md
        echo "" >> release_notes.md
        echo "## Installation" >> release_notes.md
        echo "1. Download the zip file" >> release_notes.md
        echo "2. In Kodi, go to Settings > Add-ons > Install from zip file" >> release_notes.md
        echo "3. Navigate to the downloaded zip file and select it" >> release_notes.md
        echo "4. The addon will be installed" >> release_notes.md
        
        # Create the release using GitHub CLI with full path to zip file
        gh release create "v$ADDON_VERSION" "./$ZIP_FILE" --title "Release v$ADDON_VERSION" --notes-file release_notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}